name: Docker

on:
  push:
    branches: [main]
    tags:
      - "v*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Set Docker Tag
        id: set-tag
        run: |
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
            echo "DOCKER_TAGS=ghcr.io/valentinkolb/jupyter:latest,ghcr.io/valentinkolb/jupyter:${VERSION}" >> $GITHUB_ENV
          else
            SHA=$(git rev-parse --short HEAD)
            echo "DOCKER_TAGS=ghcr.io/valentinkolb/jupyter:dev-${SHA}" >> $GITHUB_ENV
          fi

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_TAGS }}
